# Sample agent configuration
# Update the values to match your server setup

game: rust
server_id: example-server

backup:
  path: /path/to/server
  schedule:
    type: cron
    expression: "0 * * * *"
    timezone: "UTC"
  retention_days: 7

monitor:
  check_interval: 60
  crash_threshold: 3

alerts:
  enabled: true
  discord_channel: general

auth:
  token: YOUR_SECRET_TOKEN